import { Box } from '@mui/system'
import Head from 'next/head'
import React from 'react'
import Card from '../components/Card/Card'

export default function Home() {
  
  
  return (
    <React.Fragment>
      <Head>
        <title>Miniso, the largest NFT marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display="flex" justifyContent="flex-end" gap="40px" paddingRight="40px">
        Sort by
        Chuyen 4 ô 
        chuyen 6 ô
      </Box>
        <Card/>
      </React.Fragment>
  )
}
